name: Deploy Node API to ECR (OIDC)

on:
  push:
    branches:
      - aws-production-env

env:
  AWS_REGION: us-east-1
  AWS_IAM_ROLE: arn:aws:iam::904233122127:role/github-actions-deployer
  ECR_REPOSITORY_NAME_NODE: nguyen1976/trello-node

jobs:
  build_and_push_ecr:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      # 1️⃣ Checkout source code
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2️⃣ Configure AWS credentials (OIDC)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          audience: sts.amazonaws.com

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4️⃣ Lấy version từ version.txt
      - name: Read version from file
        id: version
        run: |
          VERSION=$(cat version.txt | tr -d '\n')
          echo "Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT


        #5️⃣ Tạo và push Git tag tương ứng
      - name: Create and push Git tag
        run: |
          VERSION=${{ steps.version.outputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Xóa tag local nếu trùng
          git tag -d $VERSION 2>/dev/null || true
          git tag $VERSION
          git push origin $VERSION
          echo "✅ Created and pushed Git tag: $VERSION"

      # 5️⃣ Build Docker image
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_NAME_NODE }}:$IMAGE_TAG .

      # 6️⃣ Push Docker image lên ECR
      - name: Tag and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY_NAME_NODE }}:$IMAGE_TAG
          docker tag ${{ env.ECR_REPOSITORY_NAME_NODE }}:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI
          echo "✅ Successfully pushed: $IMAGE_URI"
